version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    environment:
      - APP_KEY=$APP_KEY
      - DB_HOST=db
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - DB_DATABASE=$DB_NAME
      - DB_USERNAME=$DB_USER
      - DB_PASSWORD=$DB_PWD
      - APP_DEBUG=true
      - DEFAULT_LANGUAGE=$LANGUAGE
      - TZ=$TIMEZONE
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PWD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PWD
      - MYSQL_DATABASE=$DB_NAME
      - TZ=$TIMEZONE
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db:
